// User roles and types
export const USER_ROLES = {
  ADMIN: 'ADMIN',
  BASE_COMMANDER: 'BASE_COMMANDER',
  LOGISTICS_OFFICER: 'LOGISTICS_OFFICER'
};

export const ASSET_TYPES = {
  VEHICLE: 'VEHICLE',
  WEAPON: 'WEAPON',
  AMMUNITION: 'AMMUNITION',
  EQUIPMENT: 'EQUIPMENT'
};

export const ASSET_STATUS = {
  AVAILABLE: 'AVAILABLE',
  ASSIGNED: 'ASSIGNED',
  MAINTENANCE: 'MAINTENANCE',
  EXPENDED: 'EXPENDED'
};

export const PURCHASE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  DELIVERED: 'DELIVERED'
};

export const TRANSFER_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  IN_TRANSIT: 'IN_TRANSIT',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED'
};

export const ASSIGNMENT_STATUS = {
  ACTIVE: 'ACTIVE',
  RETURNED: 'RETURNED',
  EXPENDED: 'EXPENDED',
  DAMAGED: 'DAMAGED'
};